# Project: Proyecto
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Main.o
LINKOBJ  = Main.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -L"C:/Users/Alan/Documents/ESCOM/5to/redes/P1/C/npcap-sdk-1.06/Lib" ../P1/C/npcap-sdk-1.06/Lib/wpcap.lib -m32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Alan/Documents/ESCOM/5to/redes/P1/C/npcap-sdk-1.06/Include" -I"C:/Users/Alan/Documents/ESCOM/5to/redes/P1/C/npcap-sdk-1.06/Include/pcap"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/Alan/Documents/ESCOM/5to/redes/P1/C/npcap-sdk-1.06/Include" -I"C:/Users/Alan/Documents/ESCOM/5to/redes/P1/C/npcap-sdk-1.06/Include/pcap"
BIN      = Proyecto.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Main.o: Main.c
	$(CC) -c Main.c -o Main.o $(CFLAGS)
